"""Planar Pythagorean-hodograph spline interpolation and editing.

Public namespace: :class:`CubicPHSpline`, :class:`PHBSpline`, their policy
and value types, and the documented exception hierarchies.
"""

from ph_spline.base import PHSpline
from ph_spline.bspline import (
    PHBSpline,
    PHBSplineEditTransaction,
    PHBSplineSnapshot,
)
from ph_spline.bspline_types import (
    BuildDiagnostics,
    ConstructionPolicy,
    ContinuitySpec,
    CurveLocation,
    EditingPolicy,
    EditRepair,
    EditReport,
    Frame2D,
    InsertResult,
    InversePolicy,
    LengthCoordinate,
    NumericalPolicy,
    PointHandle,
)
from ph_spline.cubic import CubicPHSpline
from ph_spline.exceptions import (
    ArcLengthInversionError,
    ArcLengthOutOfRangeError,
    ConstructionConvergenceError,
    ContinuitySpecificationError,
    ContinuityVerificationError,
    CubicPHSplineError,
    CubicPHSplineRuntimeError,
    CubicPHSplineValueError,
    DegeneratePointDataError,
    DiscontinuousDerivativeError,
    G2VerificationError,
    InsufficientPointDataError,
    InterpolationDomainError,
    InterpolationVerificationError,
    InvalidPointDataError,
    LengthResolutionError,
    LocalEditFailure,
    NonAdmissibleSegmentError,
    NonFiniteCoordinateError,
    NonRegularSplineError,
    NonSimplePointDataError,
    NumericalPrecisionError,
    ParameterOutOfRangeError,
    PHBSplineError,
    PHBSplineRuntimeError,
    PHBSplineValueError,
    PHSplineError,
    PHSplineRuntimeError,
    PHSplineValueError,
    ResourceLimitError,
    ReversalError,
    SplineConvergenceError,
    StaleHandleError,
    StaleLocationError,
    TransactionError,
    UndefinedPrincipalNormalError,
)

__version__ = "1.2.0"

__all__ = [
    "ArcLengthInversionError",
    "ArcLengthOutOfRangeError",
    "BuildDiagnostics",
    "ConstructionConvergenceError",
    "ConstructionPolicy",
    "ContinuitySpec",
    "ContinuitySpecificationError",
    "ContinuityVerificationError",
    "CubicPHSpline",
    "CubicPHSplineError",
    "CubicPHSplineRuntimeError",
    "CubicPHSplineValueError",
    "CurveLocation",
    "DegeneratePointDataError",
    "DiscontinuousDerivativeError",
    "EditRepair",
    "EditReport",
    "EditingPolicy",
    "Frame2D",
    "G2VerificationError",
    "InsertResult",
    "InsufficientPointDataError",
    "InterpolationDomainError",
    "InterpolationVerificationError",
    "InvalidPointDataError",
    "InversePolicy",
    "LengthCoordinate",
    "LengthResolutionError",
    "LocalEditFailure",
    "NonAdmissibleSegmentError",
    "NonFiniteCoordinateError",
    "NonRegularSplineError",
    "NonSimplePointDataError",
    "NumericalPolicy",
    "NumericalPrecisionError",
    "PHBSpline",
    "PHBSplineEditTransaction",
    "PHBSplineError",
    "PHBSplineRuntimeError",
    "PHBSplineSnapshot",
    "PHBSplineValueError",
    "PHSpline",
    "PHSplineError",
    "PHSplineRuntimeError",
    "PHSplineValueError",
    "ParameterOutOfRangeError",
    "PointHandle",
    "ResourceLimitError",
    "ReversalError",
    "SplineConvergenceError",
    "StaleHandleError",
    "StaleLocationError",
    "TransactionError",
    "UndefinedPrincipalNormalError",
]
